all: compile

compile:
	@gcc main.c -Wall -Werror -Wextra
	@echo "Compilation complete. Run the program with ./a.out <arg1> <arg2>"

clean:
	@rm -f a.out
	@rm -f logfile
	@echo "Cleaned up the compiled files."
